name: Terraform Deployment to Azure

on:
  workflow_dispatch:   # 👈 manually trigger karne ke liye

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Azure Login using Client Secret
      - name: Azure Login
        uses: azure/login@v1.4.6   # 👈 force v1 (client secret supported)
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5   # 👈 apni version ke hisaab se change kar lo

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 7: Terraform Apply (Auto-Approve for CI/CD)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
